package guestbook.mentions.domain;

import static java.time.LocalDateTime.now;
import static org.assertj.core.api.BDDAssertions.then;
import static org.mockito.BDDMockito.given;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class MentionTest {
    /**
     * getMentionFixture returns a default Mention object generated by Mockito.
     * @return an instance of Mention class.
     */
    public static Mention getMentionFixture() {
        Mention mention = Mockito.mock(Mention.class);
        given(mention.getId()).willReturn(1);
        given(mention.getName()).willReturn("name");
        given(mention.getContent()).willReturn("content");
        given(mention.getCreatedAt()).willReturn(now());

        return mention;
    }

    @Test
    void builder_ValidInput_ValidOutput() {
        Mention mention = Mention.builder().name("name").content("content").build();
        then(mention)
                .hasFieldOrPropertyWithValue("name", "name")
                .hasFieldOrPropertyWithValue("content", "content");
    }
}
